# Generated by Django 4.2.8 on 2024-01-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='District',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.district'),
        ),
    ]
