# Generated by Django 4.2.8 on 2024-01-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='District',
            new_name='district',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Other', max_length=1),
        ),
    ]
