# Generated by Django 4.2.8 on 2024-01-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_district_person_district_person_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leadershipposition')),
            ],
        ),
    ]
